Privacy Policy
___________________________________________________________________________________________________________________

Our Privacy Policy was last updated on [June 7, 2023].

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
Definitions
For the purposes of this Privacy Policy:
●	"Application" means the software program provided by the Owner and downloaded by You on any electronic device, named [WORD-PLAYER].
●	"Owner" (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to [NGUYEN MINH TRIEC (MR) & PARTNERS].
●	"Country" refers to [VIETNAM], the Owner’ nationality.
●	"Device" means any device that can access the Service such as a computer, a cell phone or a digital tablet.
●	"Personal Data" is any information that relates to an identified or identifiable individual.
●	"Usage Data" refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
●	"You" means the individual accessing or using the Service, or from  the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Collecting and Using Your Personal Data
Types of Data Collected
Personal Data
The Application will not collect any personal data from You as the Application’s users.
Personally identifiable information may include, but is not limited to:
●	Email address
●	First name and last name
●	Phone number
●	Address, State, Province, ZIP/Postal code, City
●	Usage Data
Usage Data
The Application will not collect any usage data while You use it.
Usage Data may include, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
Use of Your Personal Data
The Application does not collect Personal Information and Usage Information from users. Therefore, use of users’ information is not applied in this Privacy Policy.
Retention of Your Personal Data
Not applied in this Privacy Policy.
Transfer of Your Personal Data
Not applied in this Privacy Policy.
Disclosure of Your Personal Data
Not applied in this Privacy Policy.
Security of Your Personal Data
Not applied in this Privacy Policy.
Detailed Information on the Processing of Your Personal Data
Not applied in this Privacy Policy.

Analytics
Not applied in this Privacy Policy.
Email Marketing
Not applied in this Privacy Policy.
Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
Contact Us
If you have any questions about this Privacy Policy, You can contact us:
●	By visiting this page on our website: [https://nguyenminhtriec.github.io]
●	By sending us an email: [nguyenminhtriec3618@gmail.com]
